### ISSUE TITLE
Sort by object attribute and slice collection do not work if data source is 4D

### ISSUE THREAD

**Issue by Angelo4D** [Wakanda/wakanda-issues#242]
Hello,

Having 4D as data source, sorting by object attribute and slicing a collection do not work.

Essentially I make a call to a 4D table, then in Wakanda I want to sort by an attribute of an object field and then slice it.

Since the collection is already in Wakanda it would make sense that Wakanda do the sorting and slicing job.

```
var ConCol = ds.CUSTOMERS.query("Customer_ID > 40 && Customer_ID < 50"); // CUSTOMERS is a 4D table
ConCol = ConCol.orderBy('Details.visits DESC'); // Details is an object field in 4D

SliceConcol = ConCol.slice(0,2);
```

The actual results are as follow:
- Instead of descending sorting by Details.visits, it sorts by the primary key in descending order.
- SliceConcol.length should return 2, but instead it returns 9, the length of the initial collection.

Regards,

Angelo

**Comment by hamzahik** [comment]
@JegoYann is this the same as #233  ?

**Comment by JegoYann** [comment]
@hamzahik I don't think so. #233 was fixed with v2.4.0

@Angelo4D Which Wakanda version do you use ? Did you try with v2.4.0 ?

**Comment by JegoYann** [comment]
@Angelo4D I don't see any issue with the `orderBy('obj.att desc')` and `slice(0,2)` use cases.

Here is my try on remote 4D:

```
var coll = ds.Employee.query('ID > 25').orderBy('attributs.id desc');
coll.slice(0,2)
```

Could you send us your solution if you still reproduce with Wakanda Enterprise v2.4.0 ?

**Comment by Angelo4D** [comment]
Hi,

I've tried with 2.4.0 and the result is the same, I tried with 2 object field attributes, one date type and the other long integer. However it always sort by the primary key.

Using 4D v16R6 the slicing issue is gone, therefore I conclude that the slicing is done in the 4D side, and it is possible now thanks to the Collections feature.

**Comment by Angelo4D** [comment]
Hi, 

Here is a test 4D database and Wakanda solution.

[WAK_orderby.zip](https://github.com/Wakanda/wakanda-issues/files/1762396/WAK_orderby.zip)

To test, run the script /backend/tests/test_orderby.js

You will notice that it always sort by the primary key.

**Comment by franak** [comment]
Yes, still happen in wakanda 2.4.0 and 4D v16.3
slice() do not limit the collection:
myCollection return 30 entities
myNewCollection = myCollection.slice(0,10) return the same 30 entities

**Comment by JegoYann** [comment]
Here is my result with the `slice` method with 4D v16 R6 (beta version).

![screen shot 2018-02-28 at 09 52 09](https://user-images.githubusercontent.com/3337770/36778508-2dab3330-1c6d-11e8-9132-36be60655815.png)

As you said @Angelo4D, it is a 4D issue. 4D v16.3 does not have the `slice` method. It has been introduce with 4D V16 R5 (stable version). Try it, it should solve your issue.

**Comment by Angelo4D** [comment]
Hi Yann, 

Slice issue: solved.

Now we have the sorting issue. You will notice that it is not sorting by Details.visits (34,54,28,16,38), but it sorts by the primary key.

**Comment by JegoYann** [comment]
@Angelo4D
Right, I confirm your diagnosis. This is reproducible on a Wakanda-to-Wakanda connection too.

**Comment by JegoYann** [comment]
Hello @Angelo4D ,
This issue is fixed with v2.5.0.

Regards,
Yann

**Comment by Angelo4D** [comment]
@JegoYann  that's awesome, thank you!
